--- 
  - name: hostname   file use
    hosts: all
    tasks:
         - name: template
           template:
                src: /home/vishal/ansible-instance/host.j2
                dest: /etc/hosts
            